config/routes.rb
Rails.application.routes.draw do

  resources :pictures do
    resources :comments, :only => [:show, :create, :destroy]
  end

  resources :pictures do
    member do
      put "like", to: "pictures#upvote"
      put "dislike", to: "pictures#downvote"
    end
  end

  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create, :destroy]  
  root :to => "pictures#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  belongs_to :user
  acts_as_votable

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :commenting_users, :through => :comments, :source => :user
	belongs_to :user

	validates :artist, presence: true
	validates :title, presence: true
	# validates :url, presence: true if Proc.new {|picture| picture.image.blank? }
	validates :user_id, presence: true, numericality: {	only_integer: true}

	#validation to make sure it belongs to an actual user, not just any user_id?
	
	mount_uploader :image, ImageUploader
	acts_as_votable

	def up_score
		self.get_upvotes.size
	end

	def down_score
		self.get_downvotes.size
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :comments
	has_many :pictures
	has_many :commented_pictures, :through => :comments, :source => :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "kerry", password: "mui", only: :destroy
	before_action :get_picture, :only => [:create, :destroy]

	def get_picture
		@picture = Picture.find(params[:picture_id])
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def create
		@comment = @picture.comments.create(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to picture_path(@picture), notice: "Comment created successfully"
		else
			render "pictures/show"
		end	
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to picture_path(@picture)
	end
	

	private
		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :get_picture, :only => [:edit, :update, :show, :destroy, :upvote, :downvote]

	def get_picture
		begin
			@picture = Picture.find(params[:id])
		rescue
			render "not-found"
		end
	end

	def index
		@pictures = Picture.all
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		@picture.user = current_user
		if @picture.save
			redirect_to pictures_url
		else
			render :new
		end
	end

	def update
		if @picture.update_attributes(picture_params)
			redirect_to @picture
		else
			render :edit
		end
	end
	
	def destroy
		@picture.destroy
		redirect_to pictures_url
	end

	def upvote
		@picture.liked_by current_user
		redirect_to @picture
	end

	def downvote
		@picture.downvote_from current_user
		redirect_to @picture
	end

	def edit
		
	end

	def show
			
	end

	private
	def picture_params
		params.require(:picture).permit(:artist, :title, :image)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
 		redirect_to pictures_url, :notice => "Logged in!"
 	else
 		flash.now[:alert] = "Invalid email or password"
 		render 'new'
 	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to pictures_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to pictures_url, :notice => "Signed up!"
  	else
  		render 'new'
  	end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures.paginate(page: params[:page])
  end
  
  private 
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
		<%= comment.user.email %> 	
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p> 
	<% if current_user && comment.user == current_user %>
		<%= link_to "Delete Comment", [comment.picture, comment],
			method: :delete,
			data: {confirm: "Are you sure?"} %>
	<% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@picture, @picture.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
Testing

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture, :html=> {:multipart => true} do |f| %>
	<p> 
		<%= f.label :artist %> <br>
		<%= f.text_field :artist %>
	</p>
	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.file_field :image %>
	<p>
		<%= f.submit "Save" %>
	</p>

<% end %>

app/views/pictures/_user.erb
<p class="userinfo">
  <% if current_user %>
    Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
  <% else %>
    <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
  <% end %>
</p>

app/views/pictures/edit.html.erb
<h1> Edit Picture </h1>
	<p> 
		<%= link_to "Back", @picture %>
	</p>
	<%= render "form" %>

app/views/pictures/index.html.erb
<% if current_user %>
	<%= link_to "Add a New Picture", "/pictures/new" %>
<% end %>

<div class="intro-text"> 
	<div class="row">
		<div class="large-12 columns">
			<h4> Images of the Internet </h4>
		</div>
	</div>
</div>

<div class="row">
	<ul class="small-block-grid-2-medium-block-grid-4 large-block-grid-5">
		<% @pictures.each do |picture| %>   
		<li> <%= link_to image_tag(picture.image.thumb.url), "/pictures/#{picture.id}" %> </li>
		<% end %>
	</ul>
</div>

<%= render "user" %>

app/views/pictures/new.html.erb
<h1> Add a picture </h1>

<%= link_to "Back to Pictures", pictures_url %>

<% if current_user %>
	<p>
		<% if !@picture.errors.messages.blank? %>
			<p> Oops - some errors prevented this from saving: </p>
			<% @picture.errors.full_messages.each do |message| %>
				<%= message %>
			<% end %>
		<% end %> 
	</p>

<%= render "form" %>

<% else %>
	<p> Please Log In to Add Picture </p>

<% end %>

app/views/pictures/not-found.html.erb
<h1> Sorry, <% @picture %> doesn't exist </h1>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> 

<% if current_user %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>
<% end %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>

<%= image_tag @picture.image_url(:display) %>

<div class="voting">
   	<% if current_user %>
		<%= link_to "Upvote", like_picture_path(@picture), method: :put %> <%= @picture.up_score %>
	<% else %>
		Upvote: <%= @picture.up_score %>
	<% end %>
	
	<% if current_user %>
		<%= link_to "Downvote", dislike_picture_path(@picture), method: :put %> <%= @picture.down_score %>
	<% else %>
		Downvote: <%= @picture.down_score %>
	<% end %>
</div>
	 
<br> <h4> Comments </h4> </br>

	<%= render @picture.comments %>

<% if current_user %>
	<h5> Add a comment </h5>
	<%= render 'comments/form'%>
<% else %>

<% end %>

<%= render "user" %>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class = "error_messages">
			<h2> Form is invalid </h2>
		<ul>
			<% for message in @user.errors.full_messages %>
			<li> <%= message %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="field">
	<div class="email">
		<%= f.label :email %><br>
		<%= f.text_field :email %>	
	</div>
</div>

<div class="field">
	<div class="password">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>
</div>

<div class="field">
	<div class="password_confirmation">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</div>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>